export const authConstants = {
	LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
	LOGIN_INVALID_CREDENTIALS: 'AUTH_LOGIN_INVALID_CREDENTIALS',
	LOGOUT: 'AUTH_LOGOUT',
	TOKEN_VERIFY_REQUEST: 'AUTH_TOKEN_VERIFY_REQUEST',
	TOKEN_VERIFIED: 'AUTH_TOKEN_VERIFIED',
	TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED'
	
};