export const globalConstants = {
	HIERARCHY_LOAD_REQUEST: 'GLOBAL_HIERARCHY_LOAD',
	HIERARCHY_LOAD_SUCCESS: 'GLOBAL_HIERARCHY_LOAD_SUCCESS',
	HIERARCHY_LOAD_FAILED: 'GLOBAL_HIERARCHY_LOAD_FAILED',
	SET_THEME: 'GLOBAL_SET_THEME'
};
