export const globalConstants = {
	SET_ACTIVE_QUEUE: 'GLOBAL_SET_ACTIVE_QUEUE',
	HIERARCHY_LOAD_REQUEST: 'GLOBAL_HIERARCHY_LOAD',
	HIERARCHY_LOAD_SUCCESS: 'GLOBAL_HIERARCHY_LOAD_SUCCESS',
	HIERARCHY_LOAD_FAILED: 'GLOBAL_HIERARCHY_LOAD_FAILED'
};
