export const globalConstants = {
	HIERARCHY_LOAD_REQUEST: 'GLOBAL_HIERARCHY_LOAD',
	HIERARCHY_LOAD_SUCCESS: 'GLOBAL_HIERARCHY_LOAD_SUCCESS',
	HIERARCHY_LOAD_FAILED: 'GLOBAL_HIERARCHY_LOAD_FAILED',

	LIN_QUEUES_LOAD_REQUEST: 'GLOBAL_LIN_QUEUES_LOAD',
	LIN_QUEUES_LOAD_SUCCESS: 'GLOBAL_LIN_QUEUES_LOAD_SUCCESS',
	LIN_QUEUES_LOAD_FAILED: 'GLOBAL_LIN_QUEUES_LOAD_FAILED',

	LIN_QUEUES_DISPLAY: 'GLOBAL_LIN_QUEUES_DISPLAY',
	LIN_QUEUES_HIDE: 'GLOBAL_LIN_QUEUES_HIDE',

	THEMES_DISPLAY: 'GLOBAL_THEMES_DISPLAY',
	THEMES_HIDE: 'GLOBAL_THEMES_HIDE',

	SET_THEME: 'GLOBAL_SET_THEME'
};

export const themes = {
	tryhard: {
		label: 'Tryhard',
		textWhenSelected: 'Click here to pick a theme'
	},
	buzzfeed: {
		label: 'Buzzfeed',
		textWhenSelected: 'Choose theme'
	}
}

export const defaultTheme = 'tryhard'