export const attachmentUploadConstants = {
  SAVE_URL_REQUEST: 'ATTACHMENT_UPLOAD_SAVE_URL_REQUEST',
  SAVE_URL_SUCCESS: 'ATTACHMENT_UPLOAD_SAVE_URL_SUCCESS',
  SAVE_URL_FAILED: 'ATTACHMENT_UPLOAD_SAVE_URL_FAILED',
  
	RESET: 'ATTACHMENT_UPLOAD_RESET',
}
