export const boostConstants = {
	REQUEST: 'BOOST_PAGE_ADJUST_BOOST_REQUEST',
	ADJUST_BOOST_SUCCESS: 'BOOST_PAGE_ADJUST_BOOST_SUCCESS',
	PAYPAL_SUCCESS: 'BOOST_PAGE_PAYPAL_SUCCESS',
	FAILED: 'BOOST_PAGE_ADJUST_BOOST_FAILED',
	RESET: 'BOOST_PAGE_RESET'
}

export const boostStages = {
	ADJUSTING_BOOST: 'ADJUSTING_BOOST',
	PAYPAL: 'PAYPAL',
	COMPLETED: 'COMPLETED'
}
