export const boostConstants = {
	REQUEST: 'BOOST_PAGE_BOOST_REQUEST',
	SUCCESS: 'BOOST_PAGE_BOOST_SUCCESS',
	FAILED: 'BOOST_PAGE_BOOST_FAILED',
	RESET: 'BOOST_PAGE_RESET'
}

export const boostStages = {
  BOOSTING: 0,
  COMPLETED: 1
}
