export const problemPageConstants = {
	LOAD_PROBLEM_DATA_REQUEST: "PROBLEM_PAGE_LOAD_PROBLEM_DATA_REQUEST",
	LOAD_PROBLEM_DATA_SUCCESS: "PROBLEM_PAGE_LOAD_PROBLEM_DATA_SUCCESS",
	LOAD_PROBLEM_DATA_FAILED: "PROBLEM_PAGE_LOAD_PROBLEM_DATA_FAILED",

	LOAD_SUBMISSION_PAGE_REQUEST: "PROBLEM_PAGE_LOAD_SUBMISSION_PAGE_REQUEST",
	LOAD_SUBMISSION_PAGE_FAILED: "PROBLEM_PAGE_LOAD_SUBMISSION_PAGE_FAILED",
	LOAD_SUBMISSION_PAGE_SUCCESS: "PROBLEM_PAGE_LOAD_SUBMISSION_PAGE_SUCCESS",

	LOAD_REPLY_PAGE_REQUEST: "PROBLEM_PAGE_LOAD_REPLY_PAGE_REQUEST",
	LOAD_REPLY_PAGE_FAILED: "PROBLEM_PAGE_LOAD_REPLY_PAGE_FAILED",
	LOAD_REPLY_PAGE_SUCCESS: "PROBLEM_PAGE_LOAD_REPLY_PAGE",

	POST_SUBMISSION_REQUEST: "PROBLEM_PAGE_POST_SUBMISSION_REQUEST",
	POST_SUBMISSION_FAILED: "PROBLEM_PAGE_POST_SUBMISSION_FAILED",
	POST_SUBMISSION_SUCCESS: "PROBLEM_PAGE_POST_SUBMISSION_SUCCESS",

	REPLY_SUBMISSION_REQUEST: "PROBLEM_PAGE_REPLY_SUBMISSION_REQUEST",
	REPLY_SUBMISSION_FAILED: "PROBLEM_PAGE_REPLY_SUBMISSION_FAILED",
	REPLY_SUBMISSION_SUCCESS: "PROBLEM_PAGE_REPLY_SUBMISSION_SUCCESS",

	ACCEPT_SUBMISSION_REQUEST: "PROBLEM_PAGE_ACCEPT_SUBMISSION_REQUEST",
	ACCEPT_SUBMISSION_FAILED: "PROBLEM_PAGE_ACCEPT_SUBMISSION_FAILED",
	ACCEPT_SUBMISSION_SUCCESS: "PROBLEM_PAGE_ACCEPT_SUBMISSION_SUCCESS",

	SELECT_REPLY_FORM: "PROBLEM_PAGE_SELECT_REPLY_FORM",
	RESET: "PROBLEM_PAGE_RESET_PAGES"
}