export const queuePageConstants = {
	SET_ACTIVE_PAGE_REQUEST: "QUEUE_PAGE_SET_ACTIVE_PAGE_REQUEST",
	SET_ACTIVE_PAGE_SUCCESS: "QUEUE_PAGE_SET_ACTIVE_PAGE_SUCCESS",
	NETWORK_ERROR: "QUEUE_PAGE_NETWORK_ERROR",

	SET_ACTIVE_ENTRY: "QUEUE_PAGE_SET_ACTIVE_ENTRY",
	RESET: "QUEUE_PAGE_RESET_PAGES"
}
