export const submitProblemPageConstants = {
	SUBMIT_REQUEST: 'SUBMIT_PROBLEM_PAGE_SUBMIT_REQUEST',
	SUBMIT_SUCCESS: 'SUBMIT_PROBLEM_PAGE_SUBMIT_SUCCESS',
	SUBMIT_FAILED: 'SUBMIT_PROBLEM_PAGE_SUBMIT_FAILED',

	LOAD_QUEUES_REQUEST: 'SUBMIT_PROBLEM_PAGE_LOAD_QUEUES_REQUEST',
	LOAD_QUEUES_SUCCESS: 'SUBMIT_PROBLEM_PAGE_LOAD_QUEUES_SUCCESS',
	LOAD_QUEUES_FAILED: 'SUBMIT_PROBLEM_PAGE_LOAD_QUEUES_FAILED',	

	RESET: 'SUBMIT_PROBLEM_PAGE_RESET'
}

export const submitProblemStages = {
  SUBMITTING_PROBLEM: 0,
  COMPLETED: 1
}
