export const submitProblemPageConstants = {
    SUBMIT_PROBLEM_REQUEST: 'SUBMIT_PROBLEM_REQUEST',
    SUBMIT_PROBLEM_SUCCESS: 'SUBMIT_PROBLEM_SUCCESS',
    SUBMIT_PROBLEM_FAILED: 'SUBMIT_PROBLEM_FAILED'
};
