export const submitProblemPageConstants = {
	REQUEST: 'SUBMIT_PROBLEM_REQUEST',
	SUCCESS: 'SUBMIT_PROBLEM_SUCCESS',
	FAILED: 'SUBMIT_PROBLEM_FAILED',
	RESET: 'SUBMIT_PROBLEM_RESET'
}

export const submitProblemStages = {
  SUBMITTING_PROBLEM: 0,
  COMPLETED: 1
}
