export const economyPageConstants = {
	LOAD_KARMA_VALUES_REQUEST:  'LOAD_KARMA_VALUES_REQUEST',
	LOAD_KARMA_VALUES_SUCCESS:  'LOAD_KARMA_VALUES_SUCCESS',
	LOAD_KARMA_VALUES_FAILED:   'LOAD_KARMA_VALUES_FAILED'
};
