export const scoreboardPageConstants = {
	LOAD_PAGE_REQUEST: 'SCOREBOARD_PAGE_LOAD_PAGE_REQUEST',
	LOAD_PAGE_SUCCESS: 'SCOREBOARD_PAGE_LOAD_PAGE_SUCCESS',
	LOAD_PAGE_FAILED: 'SCOREBOARD_PAGE_LOAD_PAGE_FAILED',
	USER_SEARCH_REQUEST: 'SCOREBOARD_PAGE_USER_SEARCH_REQUEST',
	USER_SEARCH_SUCCESS: 'SCOREBOARD_PAGE_USER_SEARCH_SUCCESS',
	USER_SEARCH_FAILED: 'SCOREBOARD_PAGE_USER_SEARCH_FAILED',
	USER_COUNT_REQUEST: 'SCOREBOARD_PAGE_USER_COUNT_REQUEST',
	USER_COUNT_SUCCESS: 'SCOREBOARD_PAGE_USER_COUNT_SUCCESS',
	USER_COUNT_FAILED: 'SCOREBOARD_PAGE_USER_COUNT_FAILED',
	RESET: 'SCOREBOARD_PAGE_RESET'
}