export const activityPageConstants = {
	SET_ACTIVE_PAGE_REQUEST: "ACTIVITY_PAGE_SET_ACTIVE_PAGE_REQUEST",
	SET_ACTIVE_PAGE_SUCCESS: "ACTIVITY_PAGE_SET_ACTIVE_PAGE_SUCCESS",
	SET_ACTIVE_PAGE_FAILED: "ACTIVITY_PAGE_SET_ACTIVE_PAGE_FAILED",
	SET_USER: "ACTIVITY_PAGE_SET_USER",
	RESET: "ACTIVITY_PAGE_RESET_PAGES"
}
