export const personalInformationPageConstants = {
	REQUEST_FORM_FILLED: "PERSONAL_INFORMATION_PAGE_REQUEST_FORM_FILLED",

	CONFIRM_PASSWORD_REQUEST: "PERSONAL_INFORMATION_PAGE_CONFIRM_PASSWORD_REQUEST",
	CONFIRM_PASSWORD_FAILED: "PERSONAL_INFORMATION_PAGE_CONFIRM_PASSWORD_FAILED",

	CHANGE_EMAIL_REQUEST: "PERSONAL_INFORMATION_PAGE_CHANGE_EMAIL_REQUEST",
	CHANGE_EMAIL_SUCCESS: "PERSONAL_INFORMATION_PAGE_CHANGE_EMAIL_SUCCESS",
	CHANGE_EMAIL_FAILED: "PERSONAL_INFORMATION_PAGE_CHANGE_EMAIL_FAILED",

	CHANGE_PASSWORD_REQUEST: "PERSONAL_INFORMATION_PAGE_CHANGE_PASSWORD_REQUEST",
	CHANGE_PASSWORD_SUCCESS: "PERSONAL_INFORMATION_PAGE_CHANGE_PASSWORD_SUCCESS",
	CHANGE_PASSWORD_FAILED: "PERSONAL_INFORMATION_PAGE_CHANGE_PASSWORD_FAILED",

	CHANGE_USERNAME_REQUEST: "PERSONAL_INFORMATION_PAGE_CHANGE_USERNAME_REQUEST",
	CHANGE_USERNAME_SUCCESS: "PERSONAL_INFORMATION_PAGE_CHANGE_USERNAME_SUCCESS",
	CHANGE_USERNAME_FAILED: "PERSONAL_INFORMATION_PAGE_CHANGE_USERNAME_FAILED",

	CHANGE_NAMES_REQUEST: "PERSONAL_INFORMATION_PAGE_CHANGE_NAMES_REQUEST",
	CHANGE_NAMES_SUCCESS: "PERSONAL_INFORMATION_PAGE_CHANGE_NAMES_SUCCESS",
	CHANGE_NAMES_FAILED: "PERSONAL_INFORMATION_PAGE_CHANGE_NAMES_FAILED"
}

export const personalInformationPageStages = {
	SUBMITTING_FORM: 0,
	PASSWORD_CONFIRMATION: 1,
	COMPLETED: 2
}