export const transactionPageConstants = {
	LOAD_TRANSACTION_PAGE_REQUEST: "PROBLEM_PAGE_LOAD_TRANSACTION_PAGE_REQUEST",
	LOAD_TRANSACTION_PAGE_SUCCESS: "PROBLEM_PAGE_LOAD_TRANSACTION_PAGE_SUCCESS"
	LOAD_TRANSACTION_PAGE_FAILED: "PROBLEM_PAGE_LOAD_TRANSACTION_PAGE_FAILED",
}