export const confirmPasswordChangeConstants = {
	VERIFY_REQUEST: "VERIFY_PASSWORD_CHANGE_REQUEST",
	VERIFY_SUCCESS: "VERIFY_PASSWORD_CHANGE_SUCCESS",
	VERIFY_FAILED: "VERIFY_PASSWORD_CHANGE_FAILED",

	CONFIRM_REQUEST: "CONFIRM_PASSWORD_CHANGE_REQUEST",
	CONFIRM_SUCCESS: "CONFIRM_PASSWORD_CHANGE_SUCCESS",
	CONFIRM_FAILED: "CONFIRM_PASSWORD_CHANGE_FAILED",

	RESET: "PASSWORD_CHANGE_RESET"
}

export const confirmPasswordChangeStages = {
	INVALID_TOKEN: 0,
	SUBMITTING_FORM: 1,
	COMPLETED: 2
}